Repository wecode-bootcamp-korea/13-getSuperCool-frontend, pull requests merged in 2020-10, with the labels that each got.

#3 [13기 전민승] Refactor: Nav 코드 리뷰 사항 수정
  .eslintrc.json
  .gitignore
  debug.log
  package-lock.json
  package.json
  src/Pages/Components/Footer/Footer.js
  src/Pages/Components/Footer/Footer.scss
  src/Pages/Components/Nav/Logo.js
  src/Pages/Components/Nav/Logo.scss
  src/Pages/Components/Nav/Nav.js
  src/Pages/Components/Nav/Nav.scss
  src/Pages/Components/Nav/cartIcon.svg
  src/Pages/Components/Nav/facebookIcon.svg
  src/Pages/Components/Nav/instaIcon.svg
  src/Pages/Components/Nav/logo.svg
  src/Pages/Components/Nav/userIcon.svg
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/index.js
Labels: Status: 컨플릭트 해결 요청

#5 [13기 전민승] Main Layout
  debug.log
  package-lock.json
  package.json
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/index.js
Labels: Status: 리뷰 요청

#11 [13기 김보현] Refactor: 리뷰 반영
  src/Pages/Contact/Config.js
  src/Pages/Contact/Contact.js
  src/Pages/LoginRegister/Components/ForgotPw.js
  src/Pages/LoginRegister/Components/Login.js
  src/Pages/LoginRegister/Components/Register.js
  src/Pages/LoginRegister/Components/Register.scss
  src/Pages/LoginRegister/LoginRegister.js
Labels: Status: Acceped

#7 [13기 최하늘]Add : filter 기능 구현 완료 및 리팩토링 진행중
  README.md
  public/data/data.json
  public/index.html
  src/Pages/ProductList/Components/ColorOptionBox/ColorOptionBox.js
  src/Pages/ProductList/Components/ColorOptionBox/ColorOptionBox.scss
  src/Pages/ProductList/Components/Menubar/Menubar.js
  src/Pages/ProductList/Components/Menubar/Menubar.scss
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/Components/Product/Product.scss
  src/Pages/ProductList/Components/SearchBox/SearchBox.js
  src/Pages/ProductList/Components/SearchBox/SearchBox.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청, Status: 수정 요청

#8 [13기 전민승]Cart Layout
  debug.log
  src/Pages/Components/Cart.js
  src/Pages/Components/Cart.scss
  src/Pages/Components/CartEmpty.js
  src/Pages/Components/CartEmpty.scss
  src/Pages/Components/CartList.js
  src/Pages/Components/CartList.scss
  src/Pages/Components/D.js
  src/Pages/Components/D.scss
  src/Pages/Components/Nav/Nav.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/Styles/common.scss
  src/config.js
  src/index.js
Labels: Status: Acceped, Status: 리뷰 요청

#6 [13기 전민승] Footer Layout
  src/Pages/Components/Footer.js
  src/Pages/Components/Footer/Footer.js
  src/Pages/Components/Footer/Footer.scss
  src/Pages/Components/Footer/FooterLogo.js
  src/Pages/Components/Footer/FooterLogo.scss
  src/Pages/Components/Nav/Logo.scss
  src/Styles/common.scss
  src/index.js
Labels: Status: 리뷰 요청

#12 [13기 김보현] Fix: 충돌해결
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#14 [13기 최하늘] Add : Merge 후 수정 진행중
  src/Pages/Components/Footer/Footer.js
  src/Pages/Components/Footer/Footer.scss
  src/Pages/Components/Footer/FooterLogo.scss
  src/Pages/Components/Nav.js
  src/Pages/Components/Nav/Logo.js
  src/Pages/Components/Nav/Logo.scss
  src/Pages/Components/Nav/Nav.js
  src/Pages/Components/Nav/Nav.scss
  src/Pages/LoginRegister/Components/ForgotPw.js
  src/Pages/LoginRegister/Components/ForgotPw.scss
  src/Pages/LoginRegister/Components/Login.js
  src/Pages/LoginRegister/Components/Register.js
  src/Pages/LoginRegister/LoginRegister.js
  src/Pages/LoginRegister/LoginRegister.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/ProductDetails/ProductDetails.js
  src/Pages/ProductList/Components/Menubar/Menubar.scss
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/index.js
Labels: Status: 수정 요청
